djangoshop/urls.py
from django.contrib import admin
from django.urls import path,re_path,include     # 导入re_path正则匹配路径
from django.views.static import serve    # 
from django.conf import settings         # 导入配置文件信息

urlpatterns = [
    path('admin/', admin.site.urls),
    # 设置各个app的路由分发规则,
    # 需要说明的是：namespace是可选参数，它可以帮助快速定位到指定app的路由，当设置这个参数，第一个参数必须两个值，否则就会提示错误，元组第一个值指定处理app的路由，第二个值除了空可以自己命名，但是一般我们都设置为app的名称
    path('',include(('index.urls','index'),namespace='index')),
    path('showware/',include(('showware.urls','showware'),namespace='showware')),
    path('shopper/',include(('shopper.urls','shopper'),namespace='shopper')),
    # 配置媒体资源的路由信息
    re_path('media/(?P<path>.*)',serve,{'document_root':settings.MEDIA_ROOT},name='media') # document_root写错了也会导致500错误
]

index/urls.py
# index的urls配置
from django.urls import path
from .views import indexClassView

urlpatterns=[
    # path('',indexView,name='index')  直接调用方法
    path('',indexClassView.as_view(),name='index')  # 调用类的方法
]

shopper/urls.py
# shopper 的urls设置
from django.urls import path
from .views import *

urlpatterns=[
    path('.html',shopperView,name='shopper'),
    path('login.html',loginView,name='login'),
    path('logout.html',loginoutView,name='loginout'),
    path('shopcart.html',shopcartView,name='shopcart'),
    path('delete.html',shanchuView,name='delete')
]

showware/urls.py
# showware的urls设置
from django.urls import path
from .views import waredetailView,showwareView,collectView

urlpatterns=[
    path('.html',showwareView,name='showware'),
    path('waredetail.<int:wareid>.html',waredetailView,name='waredetail'),
    path('collect.html',collectView,name='collect')
]

shopper/models.py
from django.db import models
# 购物车模型和订单模型以及订单和商品信息关系表
# Create your models here.
# 定义常量用来选择订单状态时使用
STATE=(
    ('0','待支付'),
    ('1','待发货'),
    ('2','配送中'),
    ('3','已签收'),
    ('4','退货中'),
    ('5','已关闭'),
)

class shopcart_info(models.Model):
    id=models.AutoField(primary_key=True)
    nums=models.IntegerField('购买数量')
    ware_id=models.IntegerField('商品id')
    user_id=models.IntegerField('用户id')

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name='购物车信息'
        verbose_name_plural='购物车信息'

class order_info(models.Model):
    id=models.AutoField(primary_key=True)
    total_price=models.FloatField('订单总价')
    user_id=models.IntegerField('用户id')
    createtime=models.DateTimeField('下单时间',auto_now_add=True)
    state=models.IntegerField('订单状态',choices=STATE)

    def __str__(self):
        return str(self.id)

    class Mate:
        verbose_name='订单信息'
        verbose_name_plural='订单信息'

class order_ware(models.Model):
    id=models.AutoField(primary_key=True)
    ware_id=models.IntegerField('商品id')
    order_id=models.IntegerField('订单id')
    cur_price=models.FloatField('成交价格')
    num=models.IntegerField('购买数量')

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name='订单商品明细表'
        verbose_name_plural='订单商品明细表'

shopper/views.py
from django.shortcuts import render,redirect,reverse    # 从快捷方式导入重定向后者直接提供我都忍了，这个reverse的功能居然想等于模板中的url 就是将路由命名解析成路由地址
from django.contrib.auth.models import User     # 导入用户模型来查询数据
from django.contrib.auth import login,authenticate,logout  # 导入凭证的验证方法，以及登录,退出方法
from .form import *
from .models import *
from showware.models import Ware_info
from django.http import HttpResponse
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse   # 返回json作为ajax返回的结果

# 功能：登录，注销，购物车，个人中心
# 装饰器用来校验有没有登录，如果没有登录则需要跳转到指定界面，这个装饰器三个参数
# 1 function默认是None 定义装饰器执行的函数，一般不动
# 2 通过redirect_field_name默认值next实现了登录之后就会自动跳转回来
# 3 login_url 设置用户登录的url ,默认是setting.py中的配置属性LOGIN_URL 这个属性默认是没有的，需要自己增加
@login_required(login_url='/shopper/login.html')
def shopperView(request):
    """展示当前用户基本信息"""
    title="炫酷的个人中心"
    classContent="informations"
    pageNum=request.GET.get("pageNum",1)    # 订单信息的显示页数
    # 如果订单已经支付，则先将会话中的订单信息存储到库里
    buyTime=request.GET.get("buyTime",'')  # 系统订单支付时间
    payTime=request.session.get('payTime','')  # 支付返回的时间
    if buyTime and payTime and buyTime==payTime:
        payInfo=request.session.get('payInfo','')
        order_info.objects.create(**payInfo)
        del request.session['payTime']
        del request.session['payInfo']

    # 根据当前用户查询订单信息
    orderInfoList=order_info.objects.filter(user_id=request.user.id).order_by('-createtime')
    # 分页功能,如果传入的页码不是数字，则显示第一页，如果传入的页码不存在，则显示最后一页,最后返回要给界面的当前页面元素
    paginator=Paginator(orderInfoList,7)
    pages=None
    try:
        pages=paginator.page(pageNum)
    except PageNotAnInteger:
        pages=paginator.page(1)
    except EmptyPage:
        pages=paginator.page(paginator.num_pages)
    return render(request,'shopper.html',locals())

def loginView(request):
    title="正在进行炫酷的登录"
    classContent="logins"
    if request.method=="POST":
        # 获取请求参数用户名和密码
        username=request.POST.get("username","")
        password=request.POST.get("password","")
        if User.objects.filter(username=username):
            user=authenticate(username=username,password=password) # 如果给的凭据是有效的，则返回一个用户对象
            if user:
                login(request,user) # 使用内置login方法进行登录
                return redirect(reverse("shopper:shopper"))# 重定向到个人中心,这个reverse可不是反转，他的作用是将路由命名解析成路由地址
            else:
                state="用户名或者密码不正确"
        else:
            state="注册成功"
            d=dict(username=username,password=password,is_staff=1,is_active=1)
            user=User.objects.create_user(**d)  # 这个和create_superuser差别就是登录后台和是不是超级管理员两个字段的值不同
            # User.objects.create()   这个和上面create_user的区别是，create_user会自动给密码进行加密，而create会当成一般对象直接去创建存储到库里
            user.save()
    return render(request,'login.html',locals())

def loginView2(request):
    """使用loginForm类来实现登录功能"""
    title="正在登录"
    classContent="logins"
    # 处理http的post请求
    if request.method=="POST":
        infos=LoginForm(data=request.POST)   # 感觉和上面原始的区别就是这句话，原始从request里获取数据的，现在从loginForm中获取的
        # 验证表单数据是否准确
        if infos.is_valid():
            data=infos.cleaned_data
            username=data['username']
            password=data['password']
            # 查找User是否已有用户信息
            if User.objects.filter(username=username):
                user=authenticate(username=username,password=password)
                if user:
                    login(request,user)
                    return redirect(reverse("shopper:shopper"))
                else:
                    state="用户名或者密码不正确"
            else:
                state="注册成功"
                d=dict(username=username,password=password,is_staff=1,is_active=1)
                user=User.objects.create_user(**d)
                user.save()
        else:
            # 获取到的信息验证不通过，以json格式输出
            error_msg=infos.errors.as_json()
            print(error_msg)
    else:
        # 处理get请求
        infos=LoginForm()
        return render(request,"login.html",locals())




def loginoutView(request):
    # 使用内置函数logout来退出用户登录状态
    logout(request)
    return redirect(reverse('index:index'))   # 重定向到首页

@login_required(login_url='/shopper/login.html')
def shopcartView(request):
    """处理加入购物车或者是展示购物车的逻辑。这个设计当然也可以实现，但是如果我们设置专门的订单商品信息表更合理一些，记录下当时的商品价格以及优惠情况，这个后面再说"""
    title="快乐购物车"
    classContent="shopcarts"
    # 获取请求参数
    wareid=request.GET.get('wareid','')
    warenum=request.GET.get("warenum",1)
    userID=request.user.id
    # 如果商品id不为空，则进行新增到购物车，否则就是直接展示即可
    if wareid:
        shopcart_info.objects.update_or_create(user_id=userID,nums=warenum,ware_id=wareid)
        return redirect("shopper:shopcart")
    # 如果添加的id为空，则展示购物车全部信息
    shopcartAll=shopcart_info.objects.filter(user_id=userID)        # 查询当前用户的购物车信息
    waredict={x.ware_id:x.nums for x in shopcartAll} # 从当前用户的购物车获取商品id和购买数量
    wareInfoList=Ware_info.objects.filter(id__in=waredict.keys())   # 从商品id获取商品详细信息
    return render(request,'shopcart.html',locals())

def shanchuView(request):
    result={'state':'sucess'}
    userId=request.GET.get('userId','')
    wareId=request.GET.get('wareId','')
    # 这里的规则感觉有问题，源码是如果用户id不为空则删除这个用户下的所有购物车明细，如果用户id为空，商品不为空，则删除具体商品，但是购物车的明细是商品id,用户id
    # 所以应该修改为userid不能为空，当wareid为空的情况下，则删除这个用户下所有商品记录，如果不为空，则删除具体用户具体商品
    if userId and wareId:
        # 删除具体商品
        shopcart_info.objects.filter(user_id=userId,ware_id=wareId).delete()
    elif userId:
        # 删除用户下所有购物车商品
        shopcart_info.objects.filter(user_id=userId).delete()
    else:
        result={'state':'failed'}
    return JsonResponse(result)

templates/common.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- ..........标题导入静态文件.......... -->
        {% load static %}
        <title>{{ title }}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'layui/css/layui.css' %}" />
        <script type="text/javascript" src="{% static 'layui/layui.js' %}"></script>
    </head>
    <body>
        <div class="header">
            <div class="headerLayout w1200">
                <div class="headerCon">
                    <!-- ..........2 使用路由名称生成url地址.......... -->
                    <h1 class="mallLogo">
                        <a href="{% url 'index:index' %}" title="母婴商城">
                            <img src="{% static 'img/logo.png' %}" />
                        </a>
                    </h1>
                    <!-- ..........这里是搜索商品列表框，暂时先空出来 novalidate暂时先不验证.......... -->
                    <div class="mallSearch">
                        <form action="{% url 'showware:showware' %}" method="GET" class="layui-form" novalidate>
                            <input type="text" name="warename" required lay-verify="required" autocomplete="off" class="layui-input" placeholder="请输入需要的商品"/>
                            <button class="layui-btn" lay-submit lay-filter="formDemo">
                                <i class="layui-icon layui-icon-search"></i> 
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- 尤其是使用了模板语言的地方，要多注意符号两侧的空格必须空出来，否则可能会导致识别语法异常 -->
        <div class="content content-nav-base {{classContent}}">
            <div class="main-nav">
                <div class="inner-cont0">
                    <div class="inner-cont1 w1200">
                        <!--导航栏，选中的页是选中样式，其他的则是未选中样式 django内置的if语法-->
                        <div class="inner-cont2">
                            <a href="{% url 'index:index' %} " {% if classContent == '' %} class="active" {% endif %}>首页</a>
                            <a href="{% url 'showware:showware' %}" {% if classContent == 'showware' %} class="active" {% endif %}>所有商品</a>
                            <a href="{% url 'shopper:shopcart' %}" {% if classContent == 'shopcart' %} class="active" {% endif %}>购物车</a>
                            <a href="{% url 'shopper:shopper' %}" {% if classContent == 'information' %} class="active" {% endif %}>个人中心</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- 设置文件调用块，在其他html中调用此语法，即可重写此模块，有点像是接口的意思 -->
            {% block content %}{% endblock content %}
        </div>
        {% block footer %}{% endblock footer %}
        <script type="text/javascript">
            {% block script %}{% endblock script %}
        </script>
    </body>
</html>

templates/index.html
<!--1调用模板文件common.html,导入静态资源-->
{% extends 'common.html' %}
{% load static %}
<!--2 重写common中的content模块 -->
{% block content %}
<div class="category-con">
    <div class="category-banner">
        <div class="w1200">
            <img src="{% static 'img/banner1.jpg' %}">
        </div>
    </div>
</div>
<!--3 轮播图 -->
<div class="floors">
    <div class="sk">
        <div class="sk_inner w1200">
        <div class="sk_hd">
            <a href="javascript:;">
                <img src="{% static 'img/s_img1.jpg' %}">
            </a>
        </div>
        <div class="sk_bd">
            <!--轮播大图-->
            <div class="layui-carousel" id="test1">
                <div carousel-item>
                    <div class="item-box">
                        {% for ware in allTop8 %}
                        {% if forloop.counter < 5 %}  
                        <div class="item">
                            <a href="{% url 'showware:waredetail' ware.id %}">
                                <img src="{{ ware.img_main.url }}">  <!--获取商品大图可以看懂，filefied类型需要调用.url获取-->
                            </a>
                            <div class="title">{{ ware.name }}</div>
                            <div class="price">
                                <span>￥{{ ware.discount |floatformat:'2' }} </span>
                                <del>￥{{ ware.price|floatformat:'2' }}</del>
                            </div>
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                    <div class="item-box">
                        {% for ware in allTop8 %}                 
                        {% if forloop.counter > 4 %}  <!--这里的大于号小于号前后必须要有空格，否则会混在一起报错-->
                        <div class="item">
                            <a href="{% url 'showware:waredetail' ware.id %}">
                                <img src="{{ ware.img_main.url }}">
                            </a>
                            <div class="title">{{ware.name}}</div>
                            <div class="price">
                                <span>￥{{ ware.discount|floatformat:'2' }}</span>
                                <del>￥{{ ware.price|floatformat:'2' }}</del>
                            </div>
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>  
        </div>
    </div>
</div>
</div>
<!--4 分类热销功能-->
<div class="product-cont w1200" id="product-cont">
    <div class="product-item product-item1 layui-clear">
        <div class="left-title">
            <h4>一楼</h4>
            <img src="{% static 'img/icon_gou.png' %}">
            <h5>宝宝服饰</h5>
        </div>
        <div class="right-cont">
            <a href="javascript:;" class="top-img">
                <img src="{% static 'img/img12.jpg' %}" alt="">
            </a>
            <div class="img-box">
                {% for ware in etfsTop5 %}
                <a href="{% url 'showware:waredetail' ware.id %}">
                    <img src="{{ ware.img_main.url }}">
                </a>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="product-item product-item2 layui-clear">
        <div class="left-title">
            <h4><i>二楼</i></h4>
            <img src="{% static 'img/icon_gou.png' %}">
            <h5>奶粉辅食</h5>
        </div>
        <div class="right-cont">
            <a href="javascript:;" class="top-img">
                <img src="{% static 'img/img12.jpg' %}" alt="">
            </a>
            <div class="img-box">
                {% for ware in nffsTop5 %}
                <a href="{% url 'showware:waredetail' ware.id %}" >
                    <img src="{{ ware.img_main.url }}">
                </a>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="product-item product-item3 layui-clear">
        <div class="left-title">
            <h4><i>三楼</i></h4>
            <img src="{% static 'img/icon_gou.png' %}">
            <h5>宝宝用品</h5>
        </div>
        <div class="right-cont">
            <a href="javascript:;" class="top-img">
                <img src="{% static 'img/img12.jpg' %}">
            </a>
            <div class="img-box">
                {% for ware in yeypTop5 %}
                <a href="{% url 'showware:waredetail' ware.id %}">
                    <img src="{{ ware.img_main.url }}">
                </a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}
<!--5 重写的底部代码-->
{% block footer %}
<div class="footer">
    <div class="ng-promise-box">
        <div class="ng-promise w1200">
            <p class="text">
                <a class="icon1" href="javascript:;">7天无理由退换货</a>
                <a class="icon2" href="javascript:;">满99元全场免运费</a>
                <a class="icon3" style="margin-right: 0;" href="javascript:;">100%品质保证</a>
            </p>
        </div>
    </div>
    <div class="mod_help w1200">
        <p>
            <a href="javascript:;">关于本宝宝</a>
            <span>|</span>
            <a href="javascript:;">帮助中心</a>
            <span>|</span>
            <a href="javascript:;">售后服务</a>
            <span>|</span>
            <a href="javascript:;">母婴咨询</a>
            <span>|</span>
            <a href="javascript:;">关于货源</a>
        </p>
    </div>
</div>
{% endblock footer %}

{% block script %}
layui.config({
    base:'{% static 'js/' %}'
}).use(['mm','carousel'],function(){       // 导入需要的模块
    var carousel=layui.carousel,
    mm=layui.mm;
    var option={
        elem: '#test1'
        ,width: '100%'
        ,arrow: 'always'
        ,height: '298'
        ,indicator:'none'
    }
    carousel.render(option)
});
{% endblock script %}

templates/waredetail.html
{% extends 'common.html' %}
{% load static %}
{% block content %}
<div class="data-cont-wrap w1200">
    <div class="crumb">
        <a href="{% url "index:index" %}">首页</a>
        <span> > </span>
        <a href="{% url "showware:showware" %}">所有商品</a>
        <span> > </span>
        <a href="javascript:;">产品详情</a>
    </div>
    <div class="product-intro layui-clear">
        <div class="preview-wrap">
            <img height="300" width="300" src="{{ wareInfo.img_main.url }}">
        </div>
        <div class="itemInfo-wrap">
            <div class="itemInfo">
                <div class="title">
                    <h4>{{ wareInfo.name }}</h4>
                    {% if likes %}
                        <span id="collect">
                        <i class="layui-icon layui-icon-rate-solid"></i>已收藏
                        </span>
                    {% else %}
                        <span id="collect">
                            <i class="layui-icon layui-icon-rate"></i>收藏
                        </span>
                    {% endif %}
                </div>
                <div class="summary">
                    <p class="reference">
                        <span>参考价</span>
                        <del>￥{{ wareInfo.price|floatformat:'2' }}</del>
                    </p>
                    <p class="activity">
                        <span>活动价</span>
                        <strong class="price"><i>￥</i>{{ wareInfo.discount|floatformat:'2' }}</strong>
                    </p>
                    <p class="address-box">
                        <span>送&nbsp;&nbsp;&nbsp;&nbsp;至</span>
                        <input class="address"  value="陕西&nbsp;&nbsp;西安&nbsp;&nbsp;周至县"/>
                        <span>详细地址：</span>
                        <input class="address"/>
                    </p>
                </div>
                <div class="choose-attrs">
                    <div class="color layui-clear">
                        <span class="title">规&nbsp;&nbsp;&nbsp;&nbsp;格</span>
                        <div class="color-cont">
                            <span class="btn active">{{ wareInfo.size }}</span>
                        </div>
                    </div>
                </div>
                <div class="number layui-clear">
                    <span class="title">数&nbsp;&nbsp;&nbsp;&nbsp;量</span>
                    <div class="number-cont">
                        <span class="cut btn">-</span>
                        <input onkeyup="if(this.value.length==1){this.value=this.value.replace(/[^1-9]/g,'')}else{this.value=this.value.replace(/\D/g,'')}" onafterpaste="if(this.value.length==1){this.value=this.value.replace(/[^1-9]/g,'')}else{this.value=this.value.replace(/\D/g,'')}" maxlength="4" type="" id="quantity" value="1">
                        <span class="add btn">+</span>
                    </div>
                </div>
                <div class="choose-btns">
                    <a class="layui-btn layui-btn-danger car-btn">
                        <i class="layui-icon layui-icon-cart-simple"></i>加入购物车
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!--  -->
    <div class="layui-clear">
        <div class="aside">
            <h4>热销推荐</h4>
            <div class="item-list">
            {% for tuijian in recommend %}
                <div class="item">
                    <a href="{% url "showware:waredetail" tuijian.id %}">
                        <img height="280" width="280" src="{{ tuijian.img_main.url }}">
                    </a>
                    <p>
                        <span title="{{ tuijian.name }}">{{ tuijian.name|slice:":15" }}
                            {% if tuijian.name|length > 15 %}
                                ...
                            {% endif %}
                        </span>
                        <span class="pric">￥{{ tuijian.discount|floatformat:'2' }}</span>
                    </p>
                </div>
            {% endfor %}
            </div>
        </div>
        <!-- 4 -->
        <div class="detail">
            <h4>详情</h4>
            <div class="item">
                <img width="800" src="{{ wareInfo.img_detail.url }}">
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}
    layui.config({
        base:"{% static 'js/' %}"
    }).use(['mm','jquery'],function(){
        //实现数量点击加减符号的动态
        var mm=layui.mm,$=layui.$;
        var cur=$('.number-cont input').val();
        $('.number-cont .btn').on('click',function(){
            if ($(this).hasClass('add')){
                cur++;
            }else{
                if (cur>1){
                    cur--;
                }
            }
        $('.number-cont input').val(cur);
        });

        $('.layui-btn.layui-btn-danger.car-btn').on('click',function(){
            var quantity=$("#quantity").val();
            window.location="{% url 'shopper:shopcart' %}?id={{ wareInfo.id }}&quantity="+quantity;
        });

        // 为收藏按钮绑定单击事件，点击后相互切换样式，并且发送ajax请求
        $('#collect').on('click',function(){
        var url="{% url 'showware:collect' %}?id={{ wareInfo.id }}"
        $.get(url,function(data,status){
            if (status == 200){
                $('#collect').find('i').removeClass("layui-icon-rate");    // 空心收藏按钮
                $('#collect').find('i').addClass('layui-icon-rate-solid'); // 实心收藏按钮
            }
            alert(data.result);
        });
        });
    });

    function checkNum(){
    // 放到上面去引用不知道为什么没有作用，只好直接将代码放到了事件中，没有问题了，作用就是将非数字屏蔽
        if(this.value.length==1){
            this.value=this.value.replace(/[^1-9]/g,'')
        }else{
            this.value=this.value.replace(/\D/g,'')
        }
    }

{% endblock script %}

templates/warelist.html
<!--1 导入需要的资源 -->
{% extends 'common.html' %}
{% load static %}
{% block content %}
    <div class="commod-cont-wrap">
        <div class="commod-cont w1200 layui-clear">
            <div class="left-nav">
                <div class="title">{{ title }}</div>
                <div class="list-box">
                    {% for jb1 in jb1_fl %}
                        <dl>
                            <dt>{{ jb1.first }}</dt>
                            {% for all in jb_all %}
                                {% if all.first == jb1.first %}
                                    <dd>
                                        <!--请求内放入分类id 关键字默认 -->
                                        <a href="{% url 'showware:showware' %}?fl={{ all.id }}&kw={{ kw }}">{{ all.second }}</a>
                                    </dd>
                                {% endif %}
                            {% endfor %}
                        </dl>
                    {% endfor %}
                </div>
            </div>
            <!--2 -->
            <div class="right-cont-wrap">
                <div class="right-cont">
                    <div class="layui-clear">
                        <a {% if not px or px == "sold" %} class="active" {% endif %}
                                                       href="{% url 'showware:showware' %}?fl={{ fl }}&px=sold&kw={{ kw }}">销量</a>
                        <a {% if px == "price" %} class="active" {% endif %}
                                                  href="{% url 'showware:showware' %}?fl={{ fl }}&px=price&kw={{ kw }}">价格</a>
                        <a {% if px == "created" %} class="active" {% endif %}
                                                    href="{% url 'showware:showware' %}?fl={{ fl }}&px=created&kw={{ kw }}">新品</a>
                        <a {% if px == "likes" %} class="active" {% endif %}
                                                href="{% url 'showware:showware' %}?fl={{ fl }}&px=likes&kw={{ kw }}">收藏</a>
                    </div>
                    <div class="prod-number">
                        <a href="javascript:;">商品列表</a>
                        <span> > </span>
                        <a href="javascript:;">共{{ wareList|length }}件商品</a>
                    </div>
                    <div class="cont-list layui-clear" id="list-cont">
                        {% for p in pages.object_list %}
                            <div class="item">
                                <div class="img">
                                    <a href="{% url 'showware:waredetail' p.id %}"><img height="280" width="280"
                                                                                        src="{{ p.img_main.url }}"></a>
                                </div>
                                <div class="text">
                                    <p class="title">{{ p.name }}</p>
                                    <p class="price">
                                        <span class="pri">￥{{ p.price|floatformat:'2' }}</span>
                                        <span class="nub">{{ p.sold }}人付款</span>
                                    </p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div id="demo0" style="text-align:center;">
                <div class="layui-box layui-laypage layui-laypage-default" id="layui-laypage-1">
                    {% if pages.has_previous %}
                        <a href="{% url 'showware:showware' %}?px={{ px }}&fl={{ fl }}&kw={{ kw }}&fy={{ pages.previous_page_number }}"
                           class="layui-laypage-prev">上一页</a>
                    {% endif %}
                    {% for page in pages.paginator.page_range %}
                        {% if pages.number == page %}
                            <span class="layui-laypage-curr"><em
                                    class="layui-laypage-em"></em><em>{{ page }}</em></span>
                        {% elif pages.number|add:'-1' == page or pages.number|add:'1' == page %}
                            <a href="{% url 'showware:showware' %}?px={{ px }}&fl={{ fl }}&kw={{ kw }}&fy={{ page }}"
                               class="">{{ page }}</a>
                        {% endif %}
                    {% endfor %}
                    {% if pages.has_next %}
                        <a href="{% url 'showware:showware' %}?px={{ px }}&fl={{ fl }}&kw={{ kw }}&fy={{ pages.next_page_number }}"
                           class="layui-laypage-next">下一页</a>
                    {% endif %}
                </div>

            </div>
        </div>
    </div>
{% endblock content %}
{% block script %}
    layui.config({
        base:'{% static 'js/' %}'
    }).use(['mm','laypage','jquery'],function(){
    var laypage=layui.laypage,$=layui.$,mm=layui.mm;
    // 如果级别树的一级标题处于关闭状态，那么取消激活样式，对于打开的级别，赋予激活样式，并将其他同级的下级隐藏
    $('.list-box dt').on('click',function(){
    if($(this).attr('off')){
    $(this).removeClass('active').siblings('dd').show()
    $(this).attr('off','')
    }else{
    $(this).addClass('active').siblings('dd').hide()
    $(this).attr('off',true)
    }
    })
    })
{% endblock script %}